<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentPedidoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['user_id']) || (! empty($this->class->fieldMappings['user_id']['nullable']) && array_key_exists('user_id', $data))) {
            $value = $data['user_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['user_id']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['user_id']->setValue($document, $return);
            $hydratedData['user_id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['cantidad']) || (! empty($this->class->fieldMappings['cantidad']['nullable']) && array_key_exists('cantidad', $data))) {
            $value = $data['cantidad'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['cantidad']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['cantidad']->setValue($document, $return);
            $hydratedData['cantidad'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['precio_unitario']) || (! empty($this->class->fieldMappings['precio_unitario']['nullable']) && array_key_exists('precio_unitario', $data))) {
            $value = $data['precio_unitario'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['precio_unitario']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['precio_unitario']->setValue($document, $return);
            $hydratedData['precio_unitario'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nombre_producto']) || (! empty($this->class->fieldMappings['nombre_producto']['nullable']) && array_key_exists('nombre_producto', $data))) {
            $value = $data['nombre_producto'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nombre_producto']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nombre_producto']->setValue($document, $return);
            $hydratedData['nombre_producto'] = $return;
        }
        return $hydratedData;
    }
}