<?php

namespace ContainerLDTTZoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NFBUE30Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NFBUE30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NFBUE30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\UsuarioController::delete' => ['privates', '.service_locator.SH7JDmS', 'get_ServiceLocator_SH7JDmSService', true],
            'App\\Controller\\UsuarioController::edit' => ['privates', '.service_locator.SH7JDmS', 'get_ServiceLocator_SH7JDmSService', true],
            'App\\Controller\\UsuarioController::index' => ['privates', '.service_locator.LDQPZVg', 'get_ServiceLocator_LDQPZVgService', true],
            'App\\Controller\\UsuarioController::new' => ['privates', '.service_locator.LDQPZVg', 'get_ServiceLocator_LDQPZVgService', true],
            'App\\Controller\\UsuarioController::show' => ['privates', '.service_locator.BlNMQFQ', 'get_ServiceLocator_BlNMQFQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\UsuarioController:delete' => ['privates', '.service_locator.SH7JDmS', 'get_ServiceLocator_SH7JDmSService', true],
            'App\\Controller\\UsuarioController:edit' => ['privates', '.service_locator.SH7JDmS', 'get_ServiceLocator_SH7JDmSService', true],
            'App\\Controller\\UsuarioController:index' => ['privates', '.service_locator.LDQPZVg', 'get_ServiceLocator_LDQPZVgService', true],
            'App\\Controller\\UsuarioController:new' => ['privates', '.service_locator.LDQPZVg', 'get_ServiceLocator_LDQPZVgService', true],
            'App\\Controller\\UsuarioController:show' => ['privates', '.service_locator.BlNMQFQ', 'get_ServiceLocator_BlNMQFQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\UsuarioController::delete' => '?',
            'App\\Controller\\UsuarioController::edit' => '?',
            'App\\Controller\\UsuarioController::index' => '?',
            'App\\Controller\\UsuarioController::new' => '?',
            'App\\Controller\\UsuarioController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\UsuarioController:delete' => '?',
            'App\\Controller\\UsuarioController:edit' => '?',
            'App\\Controller\\UsuarioController:index' => '?',
            'App\\Controller\\UsuarioController:new' => '?',
            'App\\Controller\\UsuarioController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
