<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFsC6qf1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFsC6qf1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFsC6qf1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFsC6qf1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFsC6qf1\App_KernelDevDebugContainer([
    'container.build_hash' => 'FsC6qf1',
    'container.build_id' => '48c6dd5d',
    'container.build_time' => 1661285807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFsC6qf1');
