<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUMkQx8G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUMkQx8G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUMkQx8G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUMkQx8G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUMkQx8G\App_KernelDevDebugContainer([
    'container.build_hash' => 'UMkQx8G',
    'container.build_id' => '7f78c081',
    'container.build_time' => 1661292858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUMkQx8G');
