<?php

namespace ContainerJZvFniz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xh2OofmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xh2Oofm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xh2Oofm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usuarioRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'usuarioRepository' => 'App\\Repository\\UsuarioRepository',
            'validator' => '?',
        ]);
    }
}
