<?php

namespace ContainerJZvFniz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuario2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SH7JDmS.App\Entity\Usuario' shared service.
     *
     * @return \App\Entity\Usuario
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SH7JDmS": it references class "App\\Entity\\Usuario" but no such service exists.');
    }
}
